general:
  app_title: "Prototype Full Stack Data App"
  session_dir: "app_session_data"  # Logical name; utils.session_dir() maps this under /scratch. Actually, should be used there but probably currently isn't.
  app_schema_name: "full_stack_data_app"

monitor_jobs:
  refresh_interval_seconds: 5
